const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();

// Complete Dictionary: PT -> ES
const dict = [
  // Lang & Meta
  ['lang="pt-BR"', 'lang="es"'],
  ['Programa de Calistenia para Mulheres', 'Programa de Calistenia para Mujeres'],
  
  // New strings (extracted)
  ['Como você descreveria o seu corpo atualmente?', '¿Cómo describirías tu cuerpo actualmente?'],
  ['Falsa Magra', 'Delgada con grasa localizada'],
  ['Magra', 'Delgada'],
  ['Acima do peso', 'Con sobrepeso'],
  ['Sobrepeso', 'Sobrepeso'],
  ['Qual é o corpo dos seus sonhos?', '¿Cuál es el cuerpo de tus sueños?'],
  ['Curvado', 'Con curvas'],
  ['Magro', 'Delgado'],
  ['Em forma', 'En forma'],
  ['Tonificado', 'Tonificado'],
  ['Estou bem com meu corpo', 'Estoy bien con mi cuerpo'],
  ['Há quanto tempo você estava na', '¿Hace cuánto tiempo estabas en la'],
  ['melhor forma da sua vida?', 'mejor forma de tu vida?'],
  ['1 a 2 anos atrás', 'Hace 1 a 2 años'],
  ['3 a 5 anos atrás', 'Hace 3 a 5 años'],
  ['Mais de 5 anos atrás', 'Hace más de 5 años'],
  ['Nunca', 'Nunca'],
  ['Você tem dificuldades com algum dos seguintes itens?', '¿Tienes dificultades con alguno de los siguientes elementos?'],
  ['Por favor, selecione todas as opções aplicáveis', 'Por favor, selecciona todas las opciones aplicables'],
  ['Costas sensíveis', 'Espalda sensible'],
  ['Joelhos sensíveis', 'Rodillas sensibles'],
  ['Quadril sensível', 'Cadera sensible'],
  ['Ombros e braços', 'Hombros y brazos'],
  ['Panturrilhas e tornozelos', 'Pantorrillas y tobillos'],
  ['Nenhuma das opções acima', 'Ninguna de las opciones anteriores'],
  ['Próximo passo', 'Siguiente paso'],
  ['Você se sente confortável ao se exercitar?', '¿Te sientes cómoda al hacer ejercicio?'],
  ['Sinto dor/Desconforto', 'Siento dolor/incomodidad'],
  ['Sinto alguma dificuldade', 'Siento alguna dificultad'],
  ['Sinto-me confortável', 'Me siento cómoda'],
  ['Nós cuidamos de você!', '¡Nosotros te cuidamos!'],
  ['A dor não vai te impedir. Adaptaremos seu programa para promover movimentos seguros e\r\n            suaves.', 'El dolor no te detendrá. Adaptaremos tu programa para promover movimientos seguros y suaves.'],
  ['A dor não vai te impedir. Adaptaremos seu programa para promover movimentos seguros e\n            suaves.', 'El dolor no te detendrá. Adaptaremos tu programa para promover movimientos seguros y suaves.'],

  // New fixes requested by user
  ['Digite sua idade', 'Ingresa tu edad'],
  ['Calculando seu IMC atual...', 'Calculando tu IMC actual...'],
  ['Avaliando perfil metabólico...', 'Evaluando perfil metabólico...'],
  ['Selecionando exercícios...', 'Seleccionando ejercicios...'],
  ['Finalizando seu plano personalizado...', 'Finalizando tu plan personalizado...'],
  ['calistenia.mp4', 'calisteniaMujeres.mp4'],

  ['Qual é a sua altura?', '¿Cuál es tu altura?'],
  ['Calculando seu IMC', 'Calculando tu IMC'],
  ['Qual é o seu peso agora?', '¿Cuál es tu peso ahora?'],
  ['Libra', 'Libra'],
  ['Seu IMC é', 'Tu IMC es'],
  [', que é considerado', ', que se considera'],
  ['sobrepeso', 'sobrepeso'],
  ['Mantenha-se positiva e concentre-se em uma dieta equilibrada e exercícios.', 'Mantente positiva y concéntrate en una dieta equilibrada y ejercicios.'],
  ['Qual é o seu peso alvo?', '¿Cuál es tu peso objetivo?'],
  ['Qual é a sua idade?', '¿Cuál es tu edad?'],
  ['Perguntamos sua idade para personalizar seu plano', 'Preguntamos tu edad para personalizar tu plan'],
  ['As pessoas mais velhas têm um percentual de gordura corporal mais alto do que as pessoas mais jovens com o mesmo IMC.', 'Las personas mayores tienen un porcentaje de grasa corporal más alto que las personas más jóvenes con el mismo IMC.'],
  ['Como você descreveria seu dia típico?', '¿Cómo describirías tu día típico?'],
  ['Eu passo a maior parte do dia sentado', 'Paso la mayor parte del día sentada'],
  ['Sedentário', 'Sedentario'],
  ['Atividade moderada', 'Actividad moderada'],
  ['Eu faço pausas ativas', 'Hago pausas activas'],
  ['Eu sou imparável', 'Soy imparable'],
  ['Estou de pé o dia todo', 'Estoy de pie todo el día'],
  ['Como estão seus níveis de energia durante o dia?', '¿Cómo están tus niveles de energía durante el día?'],
  ['Baixo, sinto-me cansada durante todo o dia', 'Bajo, me siento cansada todo el día'],
  ['Queda pós-almoço', 'Caída después del almuerzo'],
  ['Arrastando antes das refeições', 'Arrastrándome antes de las comidas'],
  ['Alto e estável', 'Alto y estable'],
  ['Quanto de água você bebe diariamente?', '¿Cuánta agua bebes diariamente?'],
  ['Eu só tomo café ou chá', 'Solo tomo café o té'],
  ['Cerca de 2 copos (0,5 L)', 'Cerca de 2 vasos (0.5 L)'],
  ['2 a 6 copos (0,5-1,5 L)', '2 a 6 vasos (0.5-1.5 L)'],
  ['Mais de 6 copos', 'Más de 6 vasos'],
  ['Quantas horas você costuma dormir?', '¿Cuántas horas sueles dormir?'],
  ['Menos de 5 horas', 'Menos de 5 horas'],
  ['5-6 horas', '5-6 horas'],
  ['7-8 horas', '7-8 horas'],
  ['Mais de 8 horas', 'Más de 8 horas'],
  ['Quais são suas preferências de refeição?', '¿Cuáles son tus preferencias de comida?'],
  ['Eu sou vegetariana', 'Soy vegetariana'],
  ['Verduras, grãos, mas sem carne animal', 'Verduras, granos, pero sin carne animal'],
  ['Eu sou vegana', 'Soy vegana'],
  ['Puramente à base de plantas, sem produtos de origem animal', 'Puramente a base de plantas, sin productos de origen animal'],
  ['Não contém glúten', 'Sin gluten'],
  ['Exclui produtos de grãos que contenham glúten', 'Excluye productos de granos que contengan gluten'],
  ['Sem lactose', 'Sin lactosa'],
  ['Excluir produtos lácteos', 'Excluye productos lácteos'],
  ['Sem restrições', 'Sin restricciones'],
  ['Aberto a todos os alimentos', 'Abierta a todos los alimentos'],
  ['Quais desses hábitos você tem?', '¿Cuáles de estos hábitos tienes?'],
  ['Procrastinação', 'Procrastinación'],
  ['Alimentação pouco saudável', 'Alimentación poco saludable'],
  ['Mídias sociais', 'Redes sociales'],
  ['Beber muita cafeína', 'Beber mucha cafeína'],
  ['Maratona de séries', 'Maratón de series'],
  ['Dúvida sobre si mesmo', 'Dudas sobre mí misma'],
  ['Roer as unhas', 'Morderse las uñas'],
  ['Estar atrasada', 'Llegar tarde'],
  ['Fumar', 'Fumar'],
  ['Beber álcool', 'Beber alcohol'],
  ['Nenhum deles', 'Ninguno de ellos'],
  ['Como você descreveria suas emoções?', '¿Cómo describirías tus emociones?'],
  ['Calma e sob controle', 'Tranquila y bajo control'],
  ['Ansiosa / preocupada (com frequência)', 'Ansiosa / preocupada (con frecuencia)'],
  ['Deprimida / triste', 'Deprimida / triste'],
  ['Facilmente irritável', 'Fácilmente irritable'],
  ['Entediada com a vida', 'Aburrida de la vida'],
  ['Mudanças de humor extremas', 'Cambios de humor extremos'],
  ['Outras', 'Otras'],
  ['Como o peso e o corpo afetam como você se sente em relação a si mesma?', '¿Cómo afectan el peso y el cuerpo a cómo te sientes contigo misma?'],
  ['Eu fico deprimida...', 'Me deprimo...'],
  ['Eu tento esconder meu corpo de outras pessoas...', 'Intento ocultar mi cuerpo de otras personas...'],
  ['Eu evito ir à praia ou à piscina...', 'Evito ir a la playa o a la piscina...'],
  ['Não sei ao certo, só quero me sentir melhor...', 'No estoy segura, solo quiero sentirme mejor...'],
  ['É assim que a transformação da sua vida se parece', 'Así es como se ve la transformación de tu vida'],
  ['É assim que a<br>transformação da sua vida<br>se parece', 'Así es como se ve la<br>transformación de tu vida'],
  ['É assim que a\r\n            <br>\r\n            <span class="hl">transformação da sua vida</span>\r\n            <br>\r\n            se parece', 'Así es como se ve la\n            <br>\n            <span class="hl">transformación de tu vida</span>'],
  ['Com base nas suas respostas, prevemos que você está entre as mulheres com mais chances de atingir seus objetivos!', 'Según tus respuestas, ¡predecimos que estás entre las mujeres con más posibilidades de alcanzar sus objetivos!'],
  ['Com Calistenia Asiática', 'Con Calistenia Asiática'],
  ['Sem mudanças', 'Sin cambios'],
  ['Construindo seu plano...', 'Construyendo tu plan...'],
  ['Analisando suas respostas...', 'Analizando tus respuestas...'],
  ['O último plano que você precisará para ficar em forma', 'El último plan que necesitarás para estar en forma'],
  ['Prevemos que você estará com', 'Predecimos que estarás con'],
  ['em até 21 dias', 'en hasta 21 días'],
  ['Semana 2', 'Semana 2'],
  ['Protocolo de 21 dias quase pronto!', '¡Protocolo de 21 días casi listo!'],
  ['De acordo com as suas respostas, você está pronta para ter resultados em 21 dias com o nosso programa.', 'De acuerdo con tus respuestas, estás lista para ver resultados en 21 días con nuestro programa.'],
  ['Seu perfil está pronto', 'Tu perfil está listo'],
  ['Índice de Massa Corporal (IMC)', 'Índice de Masa Corporal (IMC)'],
  ['Abaixo do peso', 'Bajo peso'],
  ['Obeso', 'Obesidad'],
  ['Alerta de Bloqueio:', 'Alerta de Bloqueo:'],
  ['Seu metabolismo entrou em modo de resistência. O excesso de peso está sobrecarregando suas articulações e travando sua energia diária. O segredo para voltar a secar é a ativação rítmica das fibras profundas, que derrete a gordura mais difícil sem o esforço exaustivo da academia.', 'Tu metabolismo entró en modo de resistencia. El exceso de peso está sobrecargando tus articulaciones y bloqueando tu energía diaria. El secreto para volver a adelgazar es la activación rítmica de las fibras profundas, que derrite la grasa más difícil sin el esfuerzo agotador del gimnasio.'],
  ['Estilo de vida', 'Estilo de vida'],
  ['Nível de condicionamento', 'Nivel de condición física'],
  ['Iniciante', 'Principiante'],
  ['Metabolismo', 'Metabolismo'],
  ['Em resistência, difícil queimar gordura', 'En resistencia, difícil quemar grasa'],
  ['Qual é o seu principal motivo para transformar o seu corpo?', '¿Cuál es tu motivo principal para transformar tu cuerpo?'],
  ['Me sentir mais confiante com o meu corpo.', 'Sentirme más segura con mi cuerpo.'],
  ['Ficar mais saudável e ter mais energia.', 'Estar más saludable y tener más energía.'],
  ['Me sentir bem nas minhas roupas.', 'Sentirme bien con mi ropa.'],
  ['Recuperar o corpo e a autoestima após o parto.', 'Recuperar mi cuerpo y mi autoestima después del parto.'],
  ['Outro.', 'Otro.'],
  ['Quão confiante você está em entrar em forma até o dia', '¿Qué tan segura estás de ponerte en forma para el'],
  ['Eu sei que consigo!', '¡Sé que puedo!'],
  ['Estou disposta a tentar algo novo!', '¡Estoy dispuesta a probar algo nuevo!'],
  ['Ainda sinto insegurança, mas quero mudar!', 'Todavía me siento insegura, ¡pero quiero cambiar!'],
  ['Seu plano de Calistenia Asiática Atlas está', 'Tu plan de Calistenia Asiática Atlas está'],
  ['Quase', 'Casi'],
  ['pronto!', '¡listo!'],
  ['Agora', 'Ahora'],
  ['Seu objetivo', 'Tu objetivo'],
  ['Peso atual', 'Peso actual'],
  ['Gordura corporal', 'Grasa corporal'],
  ['Acima do normal', 'Por encima de lo normal'],
  ['Nível de treino de calistenia', 'Nivel de entrenamiento de calistenia'],
  ['Peso desejado', 'Peso deseado'],
  ['Avançado', 'Avanzado'],
  ['Foco do Protocolo:', 'Enfoque del Protocolo:'],
  ['Autoestima e confiança corporal.', 'Autoestima y confianza corporal.'],
  ['O Protocolo foi ajustado para garantir sua constância. Você atingirá o pico de queima metabólica até o dia', 'El Protocolo fue ajustado para garantizar tu constancia. Alcanzarás el pico de quema metabólica para el día'],
  ['Método', 'Método'],
  ['sem impacto', 'sin impacto'],
  ['— seguro para qualquer idade e condição física', '— seguro para cualquier edad y condición física'],
  ['O que mais você espera alcançar com este plano?', '¿Qué más esperas lograr con este plan?'],
  ['Pode escolher várias opções', 'Puedes elegir varias opciones'],
  ['Aumentar a energia', 'Aumentar la energía'],
  ['Melhorar o sono', 'Mejorar el sueño'],
  ['Reduzir o estresse', 'Reducir el estrés'],
  ['Melhorar a postura e a mobilidade', 'Mejorar la postura y la movilidad'],
  ['Desenvolver flexibilidade', 'Desarrollar flexibilidad'],
  ['Quais são as zonas que mais a preocupam?', '¿Cuáles son las zonas que más te preocupan?'],
  ['Melhorar o corpo inteiro', 'Mejorar todo el cuerpo'],
  ['Queixo duplo', 'Papada'],
  ['Braços flácidos', 'Brazos flácidos'],
  ['Seios caídos', 'Senos caídos'],
  ['Gordura da barriga', 'Grasa del abdomen'],
  ['Gordura nos joelhos', 'Grasa en las rodillas'],
  ['Traseiro de alforje', 'Cartucheras'],
  ['Nádegas flácidas', 'Glúteos flácidos'],
  ['Parte interna da coxa', 'Parte interna del muslo'],
  ['Quais são as suas zonas alvo?', '¿Cuáles son tus zonas objetivo?'],
  ['Escolha todas as opções aplicáveis', 'Elige todas las opciones aplicables'],
  ['Barriga', 'Abdomen'],
  ['Bunda', 'Glúteos'],
  ['Pernas', 'Piernas'],
  ['Peito', 'Pecho'],
  ['Braços', 'Brazos'],
  ['Costas', 'Espalda'],

  // Previous strings
  ['Programa de Calistenia Asiática <span class="hl">para Mulheres</span>', 'Programa de Calistenia Asiática <span class="hl">para Mujeres</span>'],
  ['De acordo com sua idade', 'De acuerdo con tu edad'],
  ['TESTE DE 1 MINUTO', 'TEST DE 1 MINUTO'],
  ['Ao escolher sua idade e continuar, concorda com nossos', 'Al elegir tu edad y continuar, aceptas nuestros'],
  ['Termos de Serviço', 'Términos de Servicio'],
  ['reconhece nossa', 'reconoces nuestra'],
  ['Política de Privacidade', 'Política de Privacidad'],
  ['Política de Cookies', 'Política de Cookies'],
  ['Elas conseguiram e você também pode', 'Ellas lo lograron y tú también puedes'],
  ['Mais de 27 milhões de mulheres já transformaram suas vidas com a Calistenia Asiática', 'Más de 27 millones de mujeres ya transformaron sus vidas con la Calistenia Asiática'],
  ['Você já experimentou exercícios de calistenia?', '¿Ya has experimentado ejercicios de calistenia?'],
  ['Mulher calistenia', 'Mujer calistenia'],
  ['Você já tem a base, mas a Calistenia Asiática é diferente da calistenia comum.', 'Ya tienes la base, pero la Calistenia Asiática es diferente de la calistenia común.'],
  ['Enquanto o método tradicional foca apenas em força externa, nossa técnica ativa as <strong>fibras profundas</strong>, agindo na musculatura interna, onde eliminamos a <strong>gordura mais difícil de queimar</strong> e destravamos o seu metabolismo de forma definitiva.', 'Mientras el método tradicional se enfoca solo en la fuerza externa, nuestra técnica activa las <strong>fibras profundas</strong>, actuando en la musculatura interna, donde eliminamos la <strong>grasa más difícil de quemar</strong> y desbloqueamos tu metabolismo de forma definitiva.'],
  ['Enquanto o método tradicional foca apenas em força externa, nossa técnica ativa as', 'Mientras el método tradicional se enfoca solo en la fuerza externa, nuestra técnica activa las'],
  [', agindo na musculatura interna, onde eliminamos a', ', actuando en la musculatura interna, donde eliminamos la'],
  ['gordura mais difícil de queimar', 'grasa más difícil de quemar'],
  ['e destravamos o seu metabolismo de forma definitiva.', 'y desbloqueamos tu metabolismo de forma definitiva.'],
  ['Calistenia Asiática', 'Calistenia Asiática'],
  ['Não se preocupe, a Calistenia Asiática é perfeita para quem está começando do zero!', '¡No te preocupes, la Calistenia Asiática es perfecta para quienes están empezando desde cero!'],
  ['Calistenia significa usar apenas o peso do seu corpo, e nossa técnica simplifica tudo ao focar na ativação das <strong>fibras profundas</strong>. É o caminho mais rápido para você <strong>destravar o metabolismo</strong> e <strong>secar a barriga</strong> sem o esforço exaustivo da academia.', 'Calistenia significa usar solo el peso de tu cuerpo, y nuestra técnica lo simplifica todo al enfocarse en la activación de las <strong>fibras profundas</strong>. Es el camino más rápido para <strong>desbloquear tu metabolismo</strong> y <strong>reducir el abdomen</strong> sin el esfuerzo agotador del gimnasio.'],
  ['Calistenia significa usar apenas o peso do seu corpo, e nossa técnica simplifica tudo ao focar na ativação das', 'Calistenia significa usar solo el peso de tu cuerpo, y nuestra técnica lo simplifica todo al enfocarse en la activación de las'],
  ['fibras profundas', 'fibras profundas'],
  ['. É o caminho mais rápido para você', '. Es el camino más rápido para'],
  ['secar a barriga', 'reducir el abdomen'],
  ['sem o esforço exaustivo da academia.', 'sin el esfuerzo agotador del gimnasio.'],
  ['Calistenia Asiática para iniciantes', 'Calistenia Asiática para principiantes'],
  ['Qual é seu <span>principal objetivo</span>?', '¿Cuál es tu <span>objetivo principal</span>?'],
  ['Qual é seu', '¿Cuál es tu'],
  ['principal objetivo', 'objetivo principal'],
  ['Perder peso', 'Perder peso'],
  ['Desenvolver músculos', 'Desarrollar músculos'],
  ['Manter o peso e ficar em forma', 'Mantener el peso y mantenerse en forma'],
  ['Melhorar a aptidão física', 'Mejorar la condición física'],
  ['Continuar', 'Continuar'],
  ['CONTINUAR', 'CONTINUAR'],
  ['Sim', 'Sí'],
  ['Não', 'No'],
  ['Apenas 7 minutos por dia', 'Solo 7 minutos al día'],
  ['transformarão seu corpo e <span>destravarão o seu metabolismo</span> sem o esforço exaustivo da academia!', 'transformarán tu cuerpo y <span>desbloquearán tu metabolismo</span> sin el esfuerzo agotador del gimnasio!'],
  ['Apenas 7 minutos por dia — transformarão seu corpo e', 'Solo 7 minutos al día — transformarán tu cuerpo y'],
  ['destravarão o seu metabolismo', 'desbloquearán tu metabolismo'],
  ['O Protocolo de Calistenia Asiática utiliza ativações de fibras profundas para derreter a gordura acumulada e chapar a barriga, agindo onde os exercícios comuns de academia não conseguem chegar, de forma simples e definitiva..', 'El Protocolo de Calistenia Asiática utiliza activaciones de fibras profundas para derretir la grasa acumulada y marcar el abdomen, actuando donde los ejercicios comunes del gimnasio no pueden llegar, de forma simple y definitiva.'],
  ['Analisando seu perfil...', 'Analizando tu perfil...'],
  ['Personalizando seu plano...', 'Personalizando tu plan...'],
  ['Calculando seu metabolismo...', 'Calculando tu metabolismo...'],
  ['Pronto! Seu plano está sendo gerado', '¡Listo! Tu plan está siendo generado'],
  ['Seu plano de Calistenia Asiática está pronto!', '¡Tu plan de Calistenia Asiática está listo!'],
  ['Assista ao vídeo abaixo para entender como funciona...', 'Mira el video a continuación para entender cómo funciona...'],
  ['Obter meu plano personalizado agora', 'Obtener mi plan personalizado ahora'],
  ['Pagamento 100% seguro | Acesso Imediato', 'Pago 100% seguro | Acceso Inmediato'],
  ['Programa prático de treinos', 'Programa práctico de entrenamientos'],
  ['focados na queima de gordura e tonificação sem sobrecarregar as articulações.', 'enfocados en la quema de grasa y tonificación sin sobrecargar las articulaciones.'],
  ['Cronograma flexível', 'Cronograma flexible'],
  ['com 15 a 20 minutos de exercícios em casa por dia, sem precisar de aparelhos.', 'con 15 a 20 minutos de ejercicios en casa por día, sin necesidad de equipos.'],
  ['Guia de Alimentação Saudável:', 'Guía de Alimentación Saludable:'],
  ['Passo a passo prático de como acelerar o metabolismo sem dietas malucas.', 'Paso a paso práctico de cómo acelerar el metabolismo sin dietas extremas.'],
  ['Acesso Imediato pelo App', 'Acceso Inmediato por la App'],
  ['onde você vai acompanhar seu progresso diário direto do celular.', 'donde seguirás tu progreso diario directamente desde tu celular.'],
  ['🔥 74% de desconto apenas HOJE!', '🔥 ¡74% de descuento solo HOY!'],
  ['De R$ 147,00 por apenas', 'De R$ 147,00 por solo'],
  ['Acesso vitalício | Pagamento único (Não é mensalidade)', 'Acceso vitalicio | Pago único (No es mensualidad)'],
  ['Quero transformar meu corpo agora', 'Quiero transformar mi cuerpo ahora'],
  ['Resultados reais de mulheres como você', 'Resultados reales de mujeres como tú'],
  ['Beatriz — Perdeu 7kg em 30 dias', 'Beatriz — Perdió 7kg en 30 días'],
  ['"Eu estava estagnada com meu peso e sem tempo. A Calistenia Asiática me ajudou muito e hoje me sinto muito melhor e disposta, tudo isso treinando só 15 minutinhos por dia na minha sala!"', '"Estaba estancada con mi peso y sin tiempo. La Calistenia Asiática me ayudó mucho y hoy me siento mucho mejor y con energía, ¡todo esto entrenando solo 15 minutitos al día en mi sala!"'],
  ['Carla — Perdeu 5kg e definiu o corpo', 'Carla — Perdió 5kg y tonificó su cuerpo'],
  ['"Nunca pensei que conseguiria resultados tão bons treinando em casa. Minhas pernas e bumbum estão muito mais firmes e a barriga secou bastante. Recomendo para todas!"', '"Nunca pensé que conseguiría resultados tan buenos entrenando en casa. Mis piernas y glúteos están mucho más firmes y el abdomen se redujo bastante. ¡Lo recomiendo para todas!"'],
  ['Fernanda — Perdeu 12kg (Sem impacto)', 'Fernanda — Perdió 12kg (Sin impacto)'],
  ['"Com minha rotina corrida de mãe e trabalho, treinar 15 minutos por dia salvou minha saúde. O método sem impacto cuidou das minhas articulações, já que eu sentia dores no joelho."', '"Con mi rutina agitada de madre y trabajo, entrenar 15 minutos al día salvó mi salud. El método sin impacto cuidó mis articulaciones, ya que sentía dolores en la rodilla."'],
  ['Juliana — Perdeu 8kg após a gravidez', 'Juliana — Perdió 8kg después del embarazo'],
  ['"Depois da gravidez, foi a única coisa que funcionou para mim voltar ao meu corpo de antes. A flexibilidade do programa é incrível e o aplicativo é muito fácil de usar."', '"Después del embarazo, fue lo único que me funcionó para volver a mi cuerpo anterior. La flexibilidad del programa es increíble y la app es muy fácil de usar."'],
  ['🔥 Vagas promocionais limitadas!', '🔥 ¡Plazas promocionales limitadas!'],
  ['Sim! Quero garantir meu plano', '¡Sí! Quiero asegurar mi plan'],
  ['30 Dias de Garantia Incondicional', '30 Días de Garantía Incondicional'],
  ['Se você aplicar o método e por qualquer motivo achar que não é para você, basta nos enviar um email e devolvemos 100% do seu dinheiro, centavo por centavo. Simples assim, risco zero!', 'Si aplicas el método y por cualquier motivo sientes que no es para ti, solo envíanos un email y te devolvemos el 100% de tu dinero, centavo a centavo. ¡Así de simple, riesgo cero!'],
  ['Dúvidas Frequentes', 'Preguntas Frecuentes'],
  ['1. Preciso de equipamentos?', '1. ¿Necesito equipos?'],
  ['Não! Todo o programa foi desenvolvido usando apenas o peso do seu próprio corpo. Você pode fazer tudo na sua sala ou no quarto.', '¡No! Todo el programa fue desarrollado usando solo el peso de tu propio cuerpo. Puedes hacer todo en tu sala o en tu habitación.'],
  ['2. É seguro para quem sente dores?', '2. ¿Es seguro para quien siente dolores?'],
  ['Sim. A Calistenia Asiática utiliza movimentos focados e sem impacto, o que poupa suas articulações como joelhos e coluna.', 'Sí. La Calistenia Asiática utiliza movimientos enfocados y sin impacto, lo que cuida tus articulaciones como rodillas y columna.'],
  ['3. O pagamento é mensalidade?', '3. ¿El pago es mensual?'],
  ['Não! É um pagamento único de R$ 37,90. Você paga uma vez e tem acesso vitalício ao programa.', '¡No! Es un pago único de R$ 37,90. Pagas una vez y tienes acceso vitalicio al programa.'],
  ['Garantir meu acesso agora', 'Asegurar mi acceso ahora'],
  ['Compra segura | SSL | Risco Zero', 'Compra segura | SSL | Riesgo Cero'],
  ['Mulheres transformadas', 'Mujeres transformadas'],
  ['Calistenia Transformação', 'Calistenia Transformación'],
  ['Aplicativo no celular', 'Aplicación en el celular'],
  ['Garantia', 'Garantía'],
  ['mulheres', 'mujeres'],
  ['para Mulheres', 'para Mujeres'],
  ['Vamos personalizar seu plano?', '¿Vamos a personalizar tu plan?'],
  ['Quase lá!', '¡Casi ahí!'],
  ['Calculando seu plano personalizado', 'Calculando tu plan personalizado'],
];

// Helper: apply all translations
function translate(content) {
  let result = content;
  
  // Sort dictionary by length descending to avoid partial matches
  const sortedDict = [...dict].sort((a, b) => b[0].length - a[0].length);
  
  for (const [pt, es] of sortedDict) {
    result = result.split(pt).join(es);
  }
  return result;
}

// Reprocess pages
let processedCount = 0;
const pagesDir = path.join(ROOT, 'pages');
const esPages = path.join(ROOT, 'es', 'pages');

const pageFiles = fs.readdirSync(pagesDir).filter(f => f.endsWith('.html'));
for (const file of pageFiles) {
  const content = fs.readFileSync(path.join(pagesDir, file), 'utf8');
  const translated = translate(content);
  fs.writeFileSync(path.join(esPages, file), translated, 'utf8');
  processedCount++;
}

// Re-process index
const indexContent = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
fs.writeFileSync(path.join(ROOT, 'es', 'index.html'), translate(indexContent), 'utf8');

console.log(`✅ Total: ${processedCount + 1} arquivos traduzidos e atualizados para espanhol!`);
